services:
    mysql:
        image: mysql:latest
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - online

    php1:
        image: php:8.0-fpm
        container_name: php1
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /var/www
        environment:
            - APP_NAME=Serveur 1
        volumes:
            - ./:/var/www/
        depends_on:
            - mysql
        networks:
            - online
    php2:
        image: php:8.0-fpm
        container_name: php2
        working_dir: /var/www
        environment:
            - APP_NAME=Serveur 2
        command: php-fpm
        volumes:
            - ./:/var/www/
        depends_on:
            - mysql
        networks:
            - online

    nginx1:
        image: nginx:latest
        container_name: nginx1
        ports:
            - "80:80"
        volumes:
            - ./nginx/conf.d/:/etc/nginx/conf.d/
            - ./:/var/www/
        depends_on:
            - php1
        networks:
            - online
    nginx2:
        image: nginx:latest
        container_name: nginx2
        ports:
            - "81:81"
        volumes:
            - ./nginx/conf.d/:/etc/nginx/conf.d/
            - ./:/var/www/
        depends_on:
            - php2
        networks:
            - online

    phpmyadmin:
        image: phpmyadmin:latest
        ports:
            - "8080:80"
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: root
        networks:
            - online
        depends_on:
            - mysql

volumes:
    db_data:

networks:
    online:
        driver: bridge
