services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker_tp
      MYSQL_USER: ruben
      MYSQL_PASSWORD: ruben
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  php:
    image: php:8.0.2-fpm
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ./site:/var/www/
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/nginx/default.conf
      - ./site:/var/www/
    depends_on:
      - php

  # phpmyadmin:
  #   image: phpmyadmin:latest
  #   ports:
  #     - "8080:80"
  #   environment:
  #     PMA_HOST: mysql
  #     MYSQL_ROOT_PASSWORD: root
  #   depends_on:
  #     - mysql

volumes:
  db_data:
